### ISSUE TITLE
Investigate "yaw to amp" feature

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#58]
During driver practice, when in "Amp state" and the driver holds left trigger, the robot did not seem to yaw to the correct angle.

**Comment by noahlinton** [comment]
This is what we did in 2023



![Image](https://github.com/frc4039/2024/assets/19657478/41361e05-e56e-489c-86a5-0d1dea1e4095)

**Comment by Ben-Alderson** [comment]
The rotation angle for the amp is the same on both alliances, so there should be no need for this kind of alliance specific code in that case.

If you want to add a "face away from driver station wall" though, that will need to be different depending on alliance.

**Comment by noahlinton** [comment]
@WyattDube please read and implement. Thanks @Ben-Alderson for the consult.

**Comment by Ben-Alderson** [comment]
@noahlinton TeleopDriveCommand still uses getHeading(). This will likely go to an angle that is dependent on the boot angle of the robot. If robot code restarts, the gyro will reset to zero. There is currently no way to fix this because the "Zero Angle" button only updates the odometry angle because *we should not be using the raw gyro angle for anything*. getHeading should be removed completely. It's too much of a footgun.

**Comment by noahlinton** [comment]
@WyattDube @WaffleBottomT Wyatt, I thought you said you read this thread and removed. I have reopened this issue. Lets resolve this properly per @Ben-Alderson suggestion please.

**Comment by noahlinton** [comment]
On no, we are using getHeading() in many places.....do we need to kill all of those? Specifically DriveToNoteCommand as one example.

**Comment by noahlinton** [comment]
![Image](https://github.com/frc4039/2024/assets/19657478/eed85c7a-47d2-4870-b713-24d37414b124)

**Comment by noahlinton** [comment]
Is getHeading() a built in function as part of the libraries? If we modify it, could we mess something else up under the hood?

On Feb 29, 2024, at 6:22 AM, Ben-Alderson ***@***.***> wrote:

﻿

Maybe it would be easier to change the implementation of getHeading to use the odometry instead?
