### ISSUE TITLE
Add LED functionaility using REV Blinkin

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#63]
Need to add subsystem and commands to be able to drive LED's with blinkin. 

Please see teleop flow diagram for when LED's will be used during the match.

**Comment by noahlinton** [comment]
@maisyt here is the flow for when to use the LED


![Image](https://github.com/frc4039/2024/assets/19657478/84e6d100-909d-47e4-9043-424aa6020612)

**Comment by noahlinton** [comment]
Lets put this task on hold. Super low priority. Rumble is sufficient for driver notification.

**Comment by MarcoSienna** [comment]
Several changes were made to implement this:

Removed new sensor objects from constants class
Created a Sensors Class in util with the following members:

BeamBreakerIsBroken()
LowerBeamBreakerIsBroken()

Changed intake command to use the Sensors class to check beam breaker
Changed rumble command to use the Sensors class to check beam breaker

Removed BlinkinCommand
Updated IntakeNoteRumbleCommand to remove sequential group and use of BlinkinCommand which no longer exists.

Updated BlinkinSubsystem to behave per the following:

in the periodic member check the status of the upper beam breaker and perform the following actions
1) If beam breaker goes from open to broken blink green on and off for period defined in constants at blink period defined in constants
2) if beam breaker is broken and period has passed  set colour to green
3) if beam breaker is open set colour to rainbow.

This is ready for testing, however, if successful we need to discus this implementation amongst the programming team prior to merging into dev since it is using a periodic in a subsystem.
