### ISSUE TITLE
add controls to climber test code

### ISSUE THREAD

**Issue by noahlinton** [frc4039/2024#73]
See flow below for how we want to control climber during testing

![Image](https://github.com/frc4039/2024/assets/19657478/c2170266-cfea-4004-beb2-7ba9a648f71f)

**Comment by noahlinton** [comment]
@MarcoSienna Add your comments about climbing here.

@TravisMadill ignore the flow above. Do what Marco says.

**Comment by MarcoSienna** [comment]
Following are some of the particulars for the climb:

- Speed of the winch motor is 0.2 constant kClimberMotorSpeed
- Angle of the pivot is 162.   constant kClimberPivotAngle.
- Pivot command for climbing should be a toggle (pivot up / down) or two separate buttons one for pivot up and one for pivot down. 
- the driver should control the pivot as they will need to move the robot at the same time as it pivots up.  
- operator controls the winch motor and should have the function of both winch up and down.
- there may be a need to control the two winch motors separately instead of a leader follower setup.   This may be necessary in order to level the robot in case it is not centered on the chain.   Mechanically this is not currently possible as the two motors are on a common shaft, however, that may change.

**Comment by MarcoSienna** [comment]
Climb implementation is complete with controls updated in the WIKI.
